name       : yubikey-personalization-gui
version    : 3.1.24
release    : 4
source     :
    - https://github.com/Yubico/yubikey-personalization-gui/archive/yubikey-personalization-gui-3.1.24.tar.gz : c2fabc60d8a973c864dd44a6ffaf5a870f333ca5806892f0b7e4b63dd782d69a
license    : BSD
component  : security
summary    : Qt based Cross-Platform utility designed to facilitate re-configuration of YubiKeys.
description: |
    The YubiKey Personalization Tool is a Qt based Cross-Platform utility designed to facilitate re-configuration of YubiKeys
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(ImageMagick)
    - pkgconfig(libusb-1.0) 
    - pkgconfig(Qt5Core)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(ykpers-1)
    - libyubikey-devel
build      : |
    qmake "CONFIG += debian"
    %make
install    : |
    install -D -m0755 build/release/yubikey-personalization-gui "$installdir/usr/bin/yubikey-personalization-gui"
    install -D -m0644 resources/lin/yubikey-personalization-gui.1 "$installdir/usr/share/man/man1/yubikey-personalization-gui.1"
    install -D -m0644 resources/lin/yubikey-personalization-gui.desktop "$installdir/usr/share/applications/yubikey-personalization-gui.desktop"
    install -D -m0644 resources/lin/yubikey-personalization-gui.png "$installdir/usr/share/icons/hicolor/128x128/apps/yubikey-personalization-gui.png"
