name       : yubikey-personalization-gui
version    : 3.1.25
release    : 9
source     :
    - https://github.com/Yubico/yubikey-personalization-gui/archive/yubikey-personalization-gui-3.1.25.tar.gz : 5bd02e94752718c9d25cf3ae6af4cb81448e1b3d65c17ff2e7fa7f1fe94f1ebf
license    : BSD-2-Clause
component  : security
summary    : Qt based Cross-Platform utility designed to facilitate re-configuration
    of YubiKeys.
description: |
    The YubiKey Personalization Tool is a Qt based Cross-Platform utility designed to facilitate re-configuration of YubiKeys
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(libusb-1.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(ykpers-1)
    - libyubikey-devel
build      : |
    qmake "CONFIG += debian"
    %make
install    : |
    install -D -m00755 build/release/yubikey-personalization-gui $installdir/usr/bin/yubikey-personalization-gui
    install -D -m00644 resources/lin/yubikey-personalization-gui.1 $installdir/usr/share/man/man1/yubikey-personalization-gui.1
    install -D -m00644 resources/lin/yubikey-personalization-gui.desktop $installdir/usr/share/applications/yubikey-personalization-gui.desktop
    install -D -m00644 resources/lin/yubikey-personalization-gui.png $installdir/usr/share/icons/hicolor/128x128/apps/yubikey-personalization-gui.png
