name       : yubikey-personalization-gui
version    : 3.1.23
release    : 2
source     :
    - https://github.com/Yubico/yubikey-personalization-gui/archive/yubikey-personalization-gui-3.1.23.tar.gz : 16bdc594435a569b06a13d2e4247ac9b7ebf7405ffc41c292880022be47420c0
license    : BSD
summary    : Qt based Cross-Platform utility designed to facilitate re-configuration of YubiKeys.
description: |
    The YubiKey Personalization Tool is a Qt based Cross-Platform utility designed to facilitate re-configuration of YubiKeys
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(ImageMagick)
    - pkgconfig(libusb-1.0) 
    - pkgconfig(Qt5Core)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(ykpers-1)
    - libyubikey-devel
build      : |
    qmake "CONFIG += debian"
    %make
install    : |
    install -D -m0755 build/release/yubikey-personalization-gui "$installdir/usr/bin/yubikey-personalization-gui"
    install -D -m0644 resources/lin/yubikey-personalization-gui.1 "$installdir/usr/share/man/man1/yubikey-personalization-gui.1"
    install -D -m0644 resources/lin/yubikey-personalization-gui.desktop "$installdir/usr/share/applications/yubikey-personalization-gui.desktop"
    install -D -m0644 resources/lin/yubikey-personalization-gui.png "$installdir/usr/share/icons/hicolor/128x128/apps/yubikey-personalization-gui.png"
